# Generated by Django 6.0.2 on 2026-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_worker_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
