# Generated by Django 6.0.2 on 2026-03-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_payment_is_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='workers/'),
        ),
    ]
