# Generated by Django 6.0.2 on 2026-03-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_worker_bio_worker_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
