# Generated by Django 6.0.2 on 2026-03-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_worker_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='area',
            field=models.CharField(choices=[('Kothrud', 'Kothrud'), ('Baner', 'Baner'), ('Wakad', 'Wakad'), ('Hinjewadi', 'Hinjewadi'), ('Hadapsar', 'Hadapsar'), ('Shivajinagar', 'Shivajinagar'), ('NDARoad', 'NDA Road'), ('Uttamnagar', 'Uttamnagar')], default='Kothrud', max_length=50),
        ),
    ]
