# Generated by Django 6.0.2 on 2026-03-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_payment_refund_amount_alter_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
