# Generated by Django 6.0.2 on 2026-03-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('Morning', 'Morning (8AM - 12PM)'), ('Afternoon', 'Afternoon (12PM - 4PM)'), ('Evening', 'Evening (4PM - 8PM)')], default='Morning', max_length=20),
        ),
    ]
