# Generated by Django 6.0.1 on 2026-03-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_booking_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='max_jobs_per_day',
            field=models.IntegerField(default=3),
        ),
    ]
