# Generated by Django 6.0.2 on 2026-03-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_worker_max_jobs_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=100)),
                ('service_needed', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
